"""empty message

Revision ID: 44ed61c77b5a
Revises: c3119f91a366
Create Date: 2025-03-27 10:09:30.841624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ed61c77b5a'
down_revision = 'c3119f91a366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('character_height', sa.Float(), nullable=False))
        batch_op.drop_column('Height')
        batch_op.drop_column('History')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship_length', sa.Float(precision=10, asdecimal=2), nullable=False))
        batch_op.drop_column('length')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_length', sa.Float(precision=10, asdecimal=2), nullable=False))
        batch_op.drop_column('length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('vehicle_length')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_column('starship_length')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('History', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('character_height')
        batch_op.drop_column('history')

    # ### end Alembic commands ###
